### ISSUE TITLE
Carousel can't set Rack 6 properly

### ISSUE THREAD

**Issue by KylerBurke** [vapor-ware/synse-emulator-plugin#104]
Synse server writes to the `Carousel Rotate` device were working wonderfully,
until I tried the final `"{\"rack\":6}"`

The transaction succeeds, but it does not properly set the value of the `Get Rack Position` device. Subsequent reads of that device show it "rotating" every 5 seconds. But here's the issue:
It's cycling through racks 0-5 🤣 

The `Set Rack Position` reading has the correct value of 6. As far as I can tell, after setting that value to 6, the `Get Rack Position` value never stops iterating, and thus the carousel rotates perpetually.

**Comment by edaniszewski** [comment]
good catch, I have a good idea about what this is. just a dumb mistake on my part. i'll throw together a fix tomorrow morning
