### ISSUE TITLE
supported devices table view presentation

### ISSUE THREAD

**Issue by hoanhan101** [vapor-ware/synse-emulator-plugin#27]
In [README](https://github.com/vapor-ware/synse-emulator-plugin/blob/master/README.md), is it clearer to present 6 supported devices in a table view, such as:

Device | Type | Model
--- | --- | ---
Temperature | `temperature` | `emul8-temp`
LED | `led` | `emul8-led`
Fan | `fan` | `emul8-fan`
Airflow | `airflow`| `emul8-air`
Humidity |`humidity` | `emul8-humidity`
Pressure | `pressure` | `emul8-pressure`

instead of the current list view?
- Temperature (type: `temperature`, model: `emul8-temp`)
- LED (type: `led`, model: `emul8-led`)
- Fan (type: `fan`, model: `emul8-fan`)
- Airflow (type: `airflow`, model: `emul8-air`)
- Humidity (type: `humidity`, model: `emul8-humidity`)
- Pressure (type: `pressure`, model: `emul8-pressure`)

Can also include the support functionalities for each device in the table, as said in this note:
> All six support reading, but only the LED and Fan devices support writing.

Here is what the final result will look like:

Device | Type | Model | Supported call(s)
--- | --- | --- | ---
Temperature | `temperature` | `emul8-temp` | read
LED | `led` | `emul8-led` | read + write
Fan | `fan` | `emul8-fan` | read + write
Airflow | `airflow`| `emul8-air` | read
Humidity |`humidity` | `emul8-humidity` | read
Pressure | `pressure` | `emul8-pressure` | read

**Comment by edaniszewski** [comment]
Good thinking. Table view looks much better and easier to read. I'd maybe just change the 'supported calls' heading to 'capabilities'
