### ISSUE TITLE
Inaccurate write instructions for Lock device in README

### ISSUE THREAD

**Issue by KylerBurke** [vapor-ware/synse-emulator-plugin#36]
The README suggests writing to lock devices using a payload of 
```
{
    'action': 'state',
    'data': '<lock>, <unlock>, <pulseUnlock>'
}
```
Screenshot from README
![image](https://user-images.githubusercontent.com/9396966/50863982-38ad8a80-1366-11e9-9f93-167e4b848980.png)

However this causes an error in the Synse server logs:
```
[2019-01-08 22:36:58 +0000] - (sanic.access)[INFO] server:322: "POST http://127.0.0.1:5000/synse/v2/write/rack-1/vec/da7fbdfc8e962922685af9d0fac53379  200 122"
time="2019-01-08T22:36:59Z" level=debug msg="[data manager] fulfilling write transaction" device=da7fbdfc8e962922685af9d0fac53379 transaction=bgqic2nk9rsvprbqajug
time="2019-01-08T22:36:59Z" level=debug msg="[sdk] transaction status set to WRITING" id=bgqic2nk9rsvprbqajug
time="2019-01-08T22:36:59Z" level=debug msg="[sdk] transaction state set to ERROR" id=bgqic2nk9rsvprbqajug
time="2019-01-08T22:36:59Z" level=error msg="[data manager] failed to write to device da7fbdfc8e962922685af9d0fac53379: unsupported command for state action: state"
time="2019-01-08T22:36:59Z" level=debug msg="[sdk] transaction status set to DONE" id=bgqic2nk9rsvprbqajug
```

The command is accepted if the payload is minimized to 
``` {'action': '<lock>, <unlock>, <pulseUnlock>'}```
which is how it is used in the Synse Server tests introduced in this PR: https://github.com/vapor-ware/synse-server/pull/229/commits/b438cefd3f5dba6bd10fc4a43770638b73897991

This is conflicting with this excerpt from the [Synse API Docs](https://vapor-ware.github.io/synse-server/#write)
![image](https://user-images.githubusercontent.com/9396966/50864481-c9d13100-1367-11e9-9bfe-497f43582863.png)

The command is accepted with an omitted `data` field, or inclusion of the `data` field, and seemingly any value for `data`.

**Comment by hoanhan101** [comment]
Yes. You're correct that for lock device, the payload should only be `{'action': '<lock>, <unlock>, <pulseUnlock>'}`.

For the excerpt in Synse API Docs above, it is said later in the next 2 paragraphs that
> Some devices may only need an `action` specified. Some may need both `action` and `data` specified.

so I guess that is fine. We might need to update the wording so it's less confusing.
